window_mode:                      "fixed"
output_format:                    "curses"
debug_mode:                       False
send_thread_data:                 False
net_monitor:                      True
nat_trace:                        False
print_net_details:                False
dynamic_tcp_client_port_masking:  True
power_measure:                    True
memory_measure:                   False
disk_measure:                     True
file_measure:                     True
